apiVersion: iammanager.k8s.aws/v1alpha1
kind: IAMRole
metadata:
  name: vpc-cni-role
spec:
  assumeRolePolicyDocument:
    Version: "2012-10-17"
    Statement:
      - Effect: Allow
        Principal:
          Service:
            - eks.amazonaws.com
        Action:
          - sts:AssumeRole
  policies:
    - name: AmazonEKS_CNI_Policy
      document:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - ec2:AssignPrivateIpAddresses
              - ec2:AttachNetworkInterface
              - ec2:CreateNetworkInterface
              - ec2:DeleteNetworkInterface
              - ec2:DescribeInstances
              - ec2:DescribeTags
              - ec2:DescribeNetworkInterfaces
              - ec2:DetachNetworkInterface
              - ec2:ModifyNetworkInterfaceAttribute
              - ec2:UnassignPrivateIpAddresses
            Resource: "*"
